name: sasto_wholesale
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  smooth_star_rating: ^1.1.1
  timelines: ^0.1.0
  syncfusion_flutter_datagrid:
  http: ^0.13.2
  image_picker:
  flutter_slidable:
  provider: ^6.0.0
  shared_preferences: ^0.5.8
  sqflite: ^2.0.2+1
  photo_view:
  flutter_html:
  path_provider:
  get:
  get_storage:
  sms_autofill:
  intl:
  #pusher_websocket_flutter:
  webview_flutter:
  esewa_pnp: ^2.0.1
  carousel_slider: ^3.0.0
  #stream_chat_flutter:
  #splashscreen: ^1.3.5
  #flutter_facebook_auth:

#  pusher_client: ^2.0.0
#  pusher_channels_flutter: ^1.0.5
  pusher_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/connect_ips.html
    - assets/epay_request.html
    - assets/images/1.png
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/trade1.jpeg
    - assets/images/trade2.jpeg
    - assets/images/trade3.jpeg
    - assets/images/trade4.jpeg
    - assets/images/jacket.png
    - assets/images/shoe_thumb_1.png
    - assets/images/shoe_thumb_2.png
    - assets/images/shoe_thumb_3.png
    - assets/images/shoe_thumb_4.png
    - assets/images/shoe_thumb_5.png
    - assets/images/shoe_tilt_2.png
    - assets/images/show_1.png
    - assets/images/shooe_tilt_1.png
    - assets/images/small_tilt_shoe_1.png
    - assets/images/small_tilt_shoe_2.png
    - assets/images/small_tilt_shoe_3.png
    - assets/images/fb.png
    - assets/images/twitter.png
    - assets/images/insta.png
    - assets/images/google.png
    - assets/images/ecommerce.jpeg
    - assets/images/logo.png
    - assets/images/rfq.jpeg
    - assets/images/get_quote.jpeg
    - assets/images/china.jpeg
    - assets/images/nepal.png
    - assets/images/india.png
    - assets/images/partner1.png
    - assets/images/partner2.png
    - assets/images/partner3.png
    - assets/images/partner4.png
    - assets/images/partner5.png
    - assets/images/jacket.jpeg
    - assets/images/beauty.jpeg
    - assets/images/iphone.jpeg
    - assets/images/esewa-square.png
    - assets/images/connectips-square.png
    - assets/images/verified-supplier-badge.png
    - assets/images/supplier-mini-card-bg.png
    - assets/images/blog.jpeg
    - assets/images/electronic.jpeg
    - assets/images/men.jpeg
    - assets/images/shoes.jpeg
    - assets/images/watches.png
    - assets/images/toys.jpeg
    - assets/images/noImage.jpeg
    - assets/images/cod-square.png
    - assets/images/tick_icon.png
    - assets/esewa/
    - assets/images/welcome (1).png
    - assets/images/welcome.png
    - assets/images/empty cart.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
